### ISSUE TITLE
Teletype

### ISSUE THREAD

**Issue by VectorKappa** [VectorKappa/ZSPM-Ti-notes#1]
atom://teletype/portal/92fe8cd1-bc9c-4122-9f3b-387982ddd1ff

**Comment by VectorKappa** [comment]
atom://teletype/portal/db0b3a01-671c-4a1d-99ff-12a2d6960f20

**Comment by VectorKappa** [comment]
atom://teletype/portal/ee6eb173-60d6-4d1f-9fb0-05e24bf1101a

**Comment by eRgo35** [comment]
atom://teletype/portal/4ecc16bf-a458-40dd-a600-b79f970f888f

**Comment by VectorKappa** [comment]
atom://teletype/portal/c94c7cf4-9603-4f93-ac0e-857cfb48f4c7

**Comment by VectorKappa** [comment]
atom://teletype/portal/895ab0ef-622d-40f1-96f2-220bda8cfecf

**Comment by VectorKappa** [comment]
atom://teletype/portal/e4123f0d-883b-4831-9626-5684125c55ae

**Comment by eRgo35** [comment]
atom://teletype/portal/9cdcde9b-a5b2-42d7-b2f2-cae2fcad4e89

**Comment by eRgo35** [comment]
atom://teletype/portal/34c17ee1-f285-4df0-a37c-697c6e5e2fac

**Comment by VectorKappa** [comment]
atom://teletype/portal/1843786d-a905-4632-82db-86d2d4285797

**Comment by VectorKappa** [comment]
atom://teletype/portal/8a6c9fdc-009a-4714-8502-faf9d8a36026

**Comment by VectorKappa** [comment]
atom://teletype/portal/238939fd-f46f-41ab-994b-c0d132be8f2d

**Comment by VectorKappa** [comment]
atom://teletype/portal/687eeeac-f2d3-400e-97d2-057cc4282ecd

**Comment by VectorKappa** [comment]
atom://teletype/portal/00f88456-ba74-4d49-997f-63731e3315a8

**Comment by VectorKappa** [comment]
atom://teletype/portal/e73a90c6-7af3-450d-b181-eb077f410969

**Comment by VectorKappa** [comment]
atom://teletype/portal/0aeab090-55d0-458b-81fc-6b1bb31e15d0

**Comment by VectorKappa** [comment]
atom://teletype/portal/bfd180d8-f3c4-44a4-95a0-93f8c36b3d54

**Comment by dawidokox1** [comment]
atom://teletype/portal/8e93e6c2-3313-4da7-93ee-d2a5b6b6da4f

**Comment by dawidokox1** [comment]
Unnecessary
